#!/usr/bin/env python3
"""gen_caps.py <census_root> <caps_variant> <out.h>: turn census data into the tf2mt adapter tables (PLAN M3).

Inputs (all produced by tools/census/run-census.sh with the DXVK oracle):
  <root>/<caps_variant>/caps-*.bin      raw D3DCAPS9 (304 bytes) as returned to the game
  <root>/<caps_variant>/adapter-*.bin   raw D3DADAPTER_IDENTIFIER9 (1104 bytes, x64 layout)
  <root>/*/census-*.tsv                 keyed counters; we merge `checkformat|`, `checkdsmatch|`, `checktype|`, `checkms|`
Policy (PLAN D9): a combination is answered OK only if the oracle answered OK in a census run (so every OK row is
backed by something TF2 actually asked for). Everything else → D3DERR_NOTAVAILABLE. Conflicting answers across runs
abort the generation. MSAA is a policy (Apple GPUs: 2/4/8 samples) because the census only asks for what the current
settings need.
"""
import collections, glob, os, re, struct, sys

root, variant, out = sys.argv[1:4]
queries_out = sys.argv[4] if len(sys.argv) > 4 else None

def fourcc_or_int(s):
    if s.isdigit():
        return int(s)
    b = s.encode('latin1')
    assert len(b) == 4, s
    return b[0] | b[1] << 8 | b[2] << 16 | b[3] << 24

answers = {'fmt': {}, 'ds': {}, 'type': {}}
conflicts = []

def record(kind, key, ok):
    prev = answers[kind].get(key)
    if prev is not None and prev != ok:
        conflicts.append((kind, key, prev, ok))
    answers[kind][key] = ok

for path in sorted(glob.glob(os.path.join(root, '*', 'census-*.tsv'))):
    if path.endswith('.threads.tsv'):
        continue
    for line in open(path, errors='replace'):
        k, _, n = line.rstrip('\n').rpartition('\t')
        m = re.match(r'checkformat\|fmt=(\S+) rtype=(\d+) usage=(0x[0-9a-f]+)(?: adapterfmt=(\S+))? -> (OK|NO)$', k)
        if m:
            fmt, rt, usage, af, ans = m.groups()
            record('fmt', (fourcc_or_int(fmt), int(rt), int(usage, 16)), ans == 'OK')
            continue
        m = re.match(r'checkdsmatch\|rt=(\S+) ds=(\S+) -> (OK|NO)$', k)
        if m:
            record('ds', (fourcc_or_int(m[1]), fourcc_or_int(m[2])), m[3] == 'OK')
            continue
        m = re.match(r'checktype\|adapterfmt=(\S+) backbuffer=(\S+) windowed=(\d) devtype=(\d+) -> (OK|NO)$', k)
        if m:
            record('type', (fourcc_or_int(m[1]), fourcc_or_int(m[2]), int(m[3]), int(m[4])), m[5] == 'OK')

if conflicts:
    for c in conflicts:
        print('CONFLICT', c)
    sys.exit('census answers conflict across runs — investigate before generating')

caps = open(glob.glob(os.path.join(root, variant, 'caps-*.bin'))[0], 'rb').read()
ident = open(glob.glob(os.path.join(root, variant, 'adapter-*.bin'))[0], 'rb').read()
assert len(caps) == 304 and len(ident) == 1104, (len(caps), len(ident))
cstr = lambda b: b.split(b'\0')[0].decode('latin1')
driver, desc, devname = cstr(ident[0:512]), cstr(ident[512:1024]), cstr(ident[1024:1056])
dv, = struct.unpack_from('<q', ident, 1056)
vendor, device, subsys, rev = struct.unpack_from('<4I', ident, 1064)
guid = ident[1080:1096]
whql, = struct.unpack_from('<I', ident, 1096)

def c_bytes(b):
    return ',\n  '.join(', '.join(f'0x{x:02x}' for x in b[i:i + 16]) for i in range(0, len(b), 16))

fmt_ok = sorted(k for k, v in answers['fmt'].items() if v)
ds_ok = sorted(k for k, v in answers['ds'].items() if v)
type_ok = sorted(k for k, v in answers['type'].items() if v)

with open(out, 'w') as f:
    f.write('/* GENERATED by tools/census/gen_caps.py from census runs — do not edit. See docs/census-report.md.\n'
            f' * {len(fmt_ok)} CheckDeviceFormat OK rows (of {len(answers["fmt"])} distinct queries), {len(ds_ok)} depth-stencil matches,\n'
            f' * {len(type_ok)} CheckDeviceType combinations. */\n#pragma once\n#include <stdint.h>\n\n')
    f.write(f'#define TF2MT_ID_DRIVER      "{driver}"\n#define TF2MT_ID_DEVICENAME  "{devname.replace(chr(92), chr(92) * 2)}"\n'
            f'#define TF2MT_ID_DESCRIPTION_FALLBACK "{desc}"\n#define TF2MT_ID_DRIVERVERSION 0x{dv:x}ll\n'
            f'#define TF2MT_ID_VENDOR 0x{vendor:x}u\n#define TF2MT_ID_DEVICE 0x{device:x}u\n#define TF2MT_ID_SUBSYS 0x{subsys:x}u\n'
            f'#define TF2MT_ID_REVISION {rev}u\n#define TF2MT_ID_WHQL {whql}u\n')
    f.write('static const uint8_t TF2MT_ID_GUID[16] = { ' + ', '.join(f'0x{x:02x}' for x in guid) + ' };\n\n')
    f.write('/* D3DCAPS9 exactly as the oracle returned it to the game (x64 layout, 304 bytes). */\n')
    f.write('static const uint8_t TF2MT_CAPS[304] = {\n  ' + c_bytes(caps) + '\n};\n\n')
    f.write('/* { D3DFORMAT (or FOURCC), D3DRESOURCETYPE, D3DUSAGE } answered OK */\n')
    f.write('static const struct { uint32_t fmt, rtype, usage; } TF2MT_FORMAT_OK[] = {\n')
    f.write(''.join(f'  {{ 0x{a:08x}, {b}, 0x{c:x} }},\n' for a, b, c in fmt_ok) + '};\n\n')
    f.write('/* { render-target format, depth-stencil format } OK */\n')
    f.write('static const struct { uint32_t rt, ds; } TF2MT_DSMATCH_OK[] = {\n')
    f.write(''.join(f'  {{ 0x{a:08x}, 0x{b:08x} }},\n' for a, b in ds_ok) + '};\n\n')
    f.write('/* { adapter fmt, back buffer fmt, windowed, device type } OK */\n')
    f.write('static const struct { uint32_t adapter, backbuffer, windowed, devtype; } TF2MT_TYPE_OK[] = {\n')
    f.write(''.join(f'  {{ 0x{a:08x}, 0x{b:08x}, {c}, {d} }},\n' for a, b, c, d in type_ok) + '};\n')
if queries_out:   # golden query list for tools/census/probe.c (every census query + the reference answer)
    with open(queries_out, 'w') as q:
        q.write('# kind\targs\treference-answer (1 = OK). Generated by tools/census/gen_caps.py from census runs.\n')
        for (fmt, rt, usage), ok in sorted(answers['fmt'].items()):
            q.write(f'fmt\t{fmt}\t{rt}\t{usage}\t22\t{int(ok)}\n')
        for (rtf, dsf), ok in sorted(answers['ds'].items()):
            q.write(f'ds\t{rtf}\t{dsf}\t{int(ok)}\n')
        for (a, b, w, d), ok in sorted(answers['type'].items()):
            q.write(f'type\t{a}\t{b}\t{w}\t{d}\t{int(ok)}\n')
print(f'{out}: {len(fmt_ok)} fmt rows ({len(answers["fmt"]) - len(fmt_ok)} NO), {len(ds_ok)} ds, {len(type_ok)} type; '
      f'identity {desc!r} vendor {vendor:#x} device {device:#x}')
