#!/usr/bin/env python3
"""Extract D3D9 COM method tables from mingw-w64's d3d9.h.

Usage: gen_methods.py <d3d9.h> <out_dir>
Writes methods.h (name tables + counts) and thunks.S (generic forwarding thunks).
"""
import re, sys, os

hdr, out = sys.argv[1], sys.argv[2]
src = open(hdr).read()

blocks = {}
for m in re.finditer(r'DECLARE_INTERFACE_IID_\((\w+),\s*(\w+),.*?\)\s*\{(.*?)\};', src, re.S):
    name, parent, body = m.group(1), m.group(2), m.group(3)
    meths = re.findall(r'STDMETHOD(?:_\([^,]+,\s*(\w+)\)|\((\w+)\))', body)
    blocks[name] = (parent, [a or b for a, b in meths])

def flatten(name):
    parent, meths = blocks[name]
    if meths and meths[0] == 'QueryInterface':   # header already repeats inherited methods
        return meths
    return (flatten(parent) if parent in blocks else []) + meths

# IUnknown block is declared with a separate macro in some headers: hard-code it
blocks['IUnknown'] = (None, ['QueryInterface', 'AddRef', 'Release'])

wanted = {'d3d': 'IDirect3D9Ex', 'dev': 'IDirect3DDevice9Ex'}
os.makedirs(out, exist_ok=True)
with open(f'{out}/methods.h', 'w') as f:
    f.write('/* generated by gen_methods.py from mingw-w64 d3d9.h — do not edit */\n#pragma once\n')
    for short, iface in wanted.items():
        ms = flatten(iface)
        f.write(f'#define {short.upper()}_NMETHODS {len(ms)}\n')
        for i, m in enumerate(ms):
            f.write(f'#define {short.upper()}_{m} {i}\n')
        f.write(f'static const char *const {short}_method_names[{len(ms)}] = {{\n')
        f.write(''.join(f'  "{m}",\n' for m in ms) + '};\n')

with open(f'{out}/thunks.S', 'w') as f:
    f.write('/* generated by gen_methods.py — generic forwarding thunks.\n'
            ' * Wrapper layout: { void **vtbl; void *inner; }. Each thunk bumps a per-method\n'
            ' * call counter, swaps `this` for the inner object and tail-jumps to its vtable slot. */\n')
    f.write('\t.text\n')
    for short, iface in wanted.items():
        n = len(flatten(iface))
        f.write(f'\t.globl {short}_thunks\n\t.section .rdata\n\t.p2align 3\n{short}_thunks:\n')
        for i in range(n):
            f.write(f'\t.quad {short}_thunk_{i}\n')
        f.write('\t.text\n')
        for i in range(n):
            f.write(f'{short}_thunk_{i}:\n'
                    f'\tincq {short}_calls+{8*i}(%rip)\n'
                    f'\tmovq 8(%rcx), %rcx\n'
                    f'\tmovq (%rcx), %rax\n'
                    f'\tjmpq *{8*i}(%rax)\n')
for short, iface in wanted.items():
    print(short, iface, len(flatten(iface)))

# ---- all interfaces: index defines + name tables + "unimplemented" stubs (used by the null renderer)
ifaces = [n for n in blocks if n.startswith('IDirect3D') ]
with open(f'{out}/ifaces.h', 'w') as f:
    f.write('/* generated by gen_methods.py — per-interface method indices */\n#pragma once\n')
    f.write(f'#define NIFACES {len(ifaces)}\n')
    for k, iface in enumerate(ifaces):
        ms = flatten(iface)
        f.write(f'#define IFACE_{iface} {k}\n#define M_{iface}_N {len(ms)}\n')
        for i, m in enumerate(ms):
            f.write(f'#define M_{iface}_{m} {i}\n')
    f.write('static const char *const iface_names[NIFACES] = {' + ','.join(f'"{i}"' for i in ifaces) + '};\n')
    f.write('static const char *const *const iface_method_names[NIFACES] = {\n')
    for iface in ifaces:
        f.write('  (const char *const[]){' + ','.join(f'"{m}"' for m in flatten(iface)) + '},\n')
    f.write('};\n')
    for iface in ifaces:
        f.write(f'extern void *stubs_{iface}[{len(flatten(iface))}];\n')
with open(f'{out}/stubs.S', 'w') as f:
    f.write('/* generated by gen_methods.py — loud stubs: ecx = iface<<16 | method; jump to null_unimpl */\n')
    for k, iface in enumerate(ifaces):
        n = len(flatten(iface))
        f.write(f'\t.globl stubs_{iface}\n\t.section .rdata\n\t.p2align 3\nstubs_{iface}:\n')
        f.write(''.join(f'\t.quad stub_{iface}_{i}\n' for i in range(n)))
        f.write('\t.text\n')
        f.write(''.join(f'stub_{iface}_{i}:\n\tmovl ${(k << 16) | i}, %ecx\n\tjmp null_unimpl\n' for i in range(n)))

# ---- census thunks (tools/trace census mode): record (thread, method) via a C hook, then forward like the
# plain thunks. Win64: save the 4 integer arg registers, keep the stack 16-byte aligned for the call.
# (Floating-point args would be clobbered by the C hook; no D3D9 device/d3d method TF2 uses passes floats by value.)
with open(f'{out}/cthunks.S', 'w') as f:
    f.write('/* generated by gen_methods.py — census thunks: census_hit(iface<<16|method) then forward */\n\t.text\n')
    for k, (short, iface) in enumerate(wanted.items()):
        n = len(flatten(iface))
        f.write(f'\t.globl {short}_cthunks\n\t.section .rdata\n\t.p2align 3\n{short}_cthunks:\n')
        f.write(''.join(f'\t.quad {short}_cthunk_{i}\n' for i in range(n)))
        f.write('\t.text\n')
        for i in range(n):
            f.write(f'{short}_cthunk_{i}:\n'
                    '\tpushq %rcx\n\tpushq %rdx\n\tpushq %r8\n\tpushq %r9\n\tsubq $40, %rsp\n'
                    f'\tmovl ${(k << 16) | i}, %ecx\n\tcall census_hit\n'
                    '\taddq $40, %rsp\n\tpopq %r9\n\tpopq %r8\n\tpopq %rdx\n\tpopq %rcx\n'
                    f'\tjmpq *{short}_thunks+{8*i}(%rip)\n')
